---

name: Install software
yum: name={{ item }} state=present
with_items:
- openstack-neutron
- openstack-neutron-openvswitch
- openstack-neutron-ml2

name: openstack-command set bind_host
command: openstack-config --verbose --set /etc/neutron/neutron.conf DEFAULT bind_host $(ip addr show dev eth1 scope global | grep dynamic| sed -e 's#.*inet ##g' -e 's#/.*##g')
register: cmd
changed_when: "'changed' in cmd.stderr"

name: openstack-command set auth_strategy
command: openstack-config --verbose --set /etc/neutron/neutron.conf DEFAULT auth_strategy keystone
register: cmd
changed_when: "'changed' in cmd.stderr"

name: openstack-command set admin_tenant_name
command: openstack-config --verbose --set /etc/neutron/neutron.conf keystone_authtoken admin_tenant_name services
register: cmd
changed_when: "'changed' in cmd.stderr"

name: openstack-command set admin_user
command: openstack-config --verbose --set /etc/neutron/neutron.conf keystone_authtoken admin_user neutron
register: cmd
changed_when: "'changed' in cmd.stderr"

name: openstack-command set admin_password
command: openstack-config --verbose --set /etc/neutron/neutron.conf keystone_authtoken admin_password neutrontest
register: cmd
changed_when: "'changed' in cmd.stderr"

name: openstack-command set auth_uri
command: openstack-config --verbose --set /etc/neutron/neutron.conf keystone_authtoken auth_uri http://vip-keystone:35357/v2.0/
register: cmd
changed_when: "'changed' in cmd.stderr"

name: openstack-command set identity_uri
command: openstack-config --verbose --set /etc/neutron/neutron.conf keystone_authtoken identity_uri http://vip-keystone:5000/
register: cmd
changed_when: "'changed' in cmd.stderr"

name: openstack-command set connection
command: openstack-config --verbose --set /etc/neutron/neutron.conf database connection mysql://neutron:neutrontest@vip-db:3306/neutron
register: cmd
changed_when: "'changed' in cmd.stderr"

name: openstack-command set max_retries
command: openstack-config --verbose --set /etc/neutron/neutron.conf database max_retries -1
register: cmd
changed_when: "'changed' in cmd.stderr"

name: openstack-command set rabbit_hosts
command: openstack-config --verbose --set /etc/neutron/neutron.conf oslo_messaging_rabbit rabbit_hosts {{ PHD_VAR_network_hosts_rabbitmq }}
register: cmd
changed_when: "'changed' in cmd.stderr"

name: openstack-command set rabbit_ha_queues
command: openstack-config --verbose --set /etc/neutron/neutron.conf oslo_messaging_rabbit rabbit_ha_queues true
register: cmd
changed_when: "'changed' in cmd.stderr"

name: openstack-command set notification_driver
command: openstack-config --verbose --set /etc/neutron/neutron.conf DEFAULT notification_driver neutron.openstack.common.notifier.rpc_notifier
register: cmd
changed_when: "'changed' in cmd.stderr"

name: openstack-command set nova_url
command: openstack-config --verbose --set /etc/neutron/neutron.conf DEFAULT nova_url http://vip-nova:8774/v2
register: cmd
changed_when: "'changed' in cmd.stderr"

name: openstack-command set notify_nova_on_port_status_changes
command: openstack-config --verbose --set /etc/neutron/neutron.conf DEFAULT notify_nova_on_port_status_changes True
register: cmd
changed_when: "'changed' in cmd.stderr"

name: openstack-command set notify_nova_on_port_data_changes
command: openstack-config --verbose --set /etc/neutron/neutron.conf DEFAULT notify_nova_on_port_data_changes True
register: cmd
changed_when: "'changed' in cmd.stderr"

name: openstack-command set auth_url
command: openstack-config --verbose --set /etc/neutron/neutron.conf nova auth_url http://vip-keystone:35357/
register: cmd
changed_when: "'changed' in cmd.stderr"

name: openstack-command set auth_plugin
command: openstack-config --verbose --set /etc/neutron/neutron.conf nova auth_plugin password
register: cmd
changed_when: "'changed' in cmd.stderr"

name: openstack-command set project_domain_id
command: openstack-config --verbose --set /etc/neutron/neutron.conf nova project_domain_id default
register: cmd
changed_when: "'changed' in cmd.stderr"

name: openstack-command set user_domain_id
command: openstack-config --verbose --set /etc/neutron/neutron.conf nova user_domain_id default
register: cmd
changed_when: "'changed' in cmd.stderr"

name: openstack-command set region_name
command: openstack-config --verbose --set /etc/neutron/neutron.conf nova region_name regionOne
register: cmd
changed_when: "'changed' in cmd.stderr"

name: openstack-command set project_name
command: openstack-config --verbose --set /etc/neutron/neutron.conf nova project_name services
register: cmd
changed_when: "'changed' in cmd.stderr"

name: openstack-command set username
command: openstack-config --verbose --set /etc/neutron/neutron.conf nova username compute
register: cmd
changed_when: "'changed' in cmd.stderr"

name: openstack-command set password
command: openstack-config --verbose --set /etc/neutron/neutron.conf nova password novatest
register: cmd
changed_when: "'changed' in cmd.stderr"

name: openstack-command set core_plugin
command: openstack-config --verbose --set /etc/neutron/neutron.conf DEFAULT core_plugin neutron.plugins.ml2.plugin.Ml2Plugin
register: cmd
changed_when: "'changed' in cmd.stderr"

name: openstack-command set service_plugins
command: openstack-config --verbose --set /etc/neutron/neutron.conf DEFAULT service_plugins neutron.services.l3_router.l3_router_plugin.L3RouterPlugin
register: cmd
changed_when: "'changed' in cmd.stderr"

name: openstack-command set router_scheduler_driver
command: openstack-config --verbose --set /etc/neutron/neutron.conf DEFAULT router_scheduler_driver neutron.scheduler.l3_agent_scheduler.ChanceScheduler
register: cmd
changed_when: "'changed' in cmd.stderr"

name: openstack-command set local,gre,flat,vxlan,vlan
command: openstack-config --verbose --set /etc/neutron/plugins/ml2/ml2_conf.ini type_drivers local,gre,flat,vxlan,vlan
register: cmd
changed_when: "'changed' in cmd.stderr"

name: openstack-command set tenant_network_types
command: openstack-config --verbose --set /etc/neutron/plugins/ml2/ml2_conf.ini ml2 tenant_network_types vxlan
register: cmd
changed_when: "'changed' in cmd.stderr"

name: openstack-command set mechanism_drivers
command: openstack-config --verbose --set /etc/neutron/plugins/ml2/ml2_conf.ini ml2 mechanism_drivers openvswitch
register: cmd
changed_when: "'changed' in cmd.stderr"

name: openstack-command set flat_networks
command: openstack-config --verbose --set /etc/neutron/plugins/ml2/ml2_conf.ini ml2_type_flat flat_networks "*"
register: cmd
changed_when: "'changed' in cmd.stderr"

name: openstack-command set tunnel_id_ranges
command: openstack-config --verbose --set /etc/neutron/plugins/ml2/ml2_conf.ini ml2_type_gre tunnel_id_ranges 10:10000
register: cmd
changed_when: "'changed' in cmd.stderr"

name: openstack-command set vni_ranges
command: openstack-config --verbose --set /etc/neutron/plugins/ml2/ml2_conf.ini ml2_type_vxlan vni_ranges 10:10000
register: cmd
changed_when: "'changed' in cmd.stderr"

name: openstack-command set vxlan_group
command: openstack-config --verbose --set /etc/neutron/plugins/ml2/ml2_conf.ini ml2_type_vxlan vxlan_group 224.0.0.1
register: cmd
changed_when: "'changed' in cmd.stderr"

name: openstack-command set enable_security_group
command: openstack-config --verbose --set /etc/neutron/plugins/ml2/ml2_conf.ini securitygroup enable_security_group True
register: cmd
changed_when: "'changed' in cmd.stderr"

name: openstack-command set firewall_driver
command: openstack-config --verbose --set /etc/neutron/plugins/ml2/ml2_conf.ini securitygroup firewall_driver True
register: cmd
changed_when: "'changed' in cmd.stderr"

name: openstack-command set l3_ha
command: openstack-config --verbose --set /etc/neutron/neutron.conf DEFAULT l3_ha True
register: cmd
changed_when: "'changed' in cmd.stderr"

name: openstack-command set max_l3_agents_per_router
command: openstack-config --verbose --set /etc/neutron/neutron.conf DEFAULT max_l3_agents_per_router 0
register: cmd
changed_when: "'changed' in cmd.stderr"

name: openstack-command set min_l3_agents_per_router
command: openstack-config --verbose --set /etc/neutron/neutron.conf DEFAULT min_l3_agents_per_router 2
register: cmd
changed_when: "'changed' in cmd.stderr"

name: openstack-command set dhcp_agents_per_network
command: openstack-config --verbose --set /etc/neutron/neutron.conf DEFAULT dhcp_agents_per_network 3
register: cmd
changed_when: "'changed' in cmd.stderr"
