---

name: Install software
yum: name={{ item }} state=present
with_items:
- fence-virtd
- fence-virtd-multicast
- fence-virtd-libvirt

name: Install software
yum: name={{ item }} state=present
with_items:
[]
