---

name: Install software
yum: name={{ item }} state=present
with_items:
- nfs-utils

name: Install software
yum: name={{ item }} state=present
with_items:
- haproxy

name: Install software
yum: name={{ item }} state=present
with_items:
- bind

name: Install software
yum: name={{ item }} state=present
with_items:
- dhcp
